-- 1. 고양이와 개는 몇마리 있을까
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE) 
FROM ANIMAL_INS 
GROUP BY ANIMAL_TYPE 
ORDER BY ANIMAL_TYPE;

-- 2. 동명 동물 수 찾기
SELECT NAME, COUNT(NAME) 
FROM ANIMAL_INS 
GROUP BY NAME 
HAVING COUNT(NAME) > 1 
ORDER BY NAME;

-- 3. 입양시각구하기(1)
SELECT HOUR(DATETIME) AS H, COUNT(HOUR(DATETIME)) 
FROM ANIMAL_OUTS 
GROUP BY HOUR(DATETIME)
HAVING H BETWEEN 9 AND 20
ORDER BY HOUR(DATETIME);

-- 4. 입양시각구하기(2)
SET @H := -1;
SELECT (@H := @H + 1) AS HOUR, (SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME) = @H) AS COUNT
FROM ANIMAL_OUTS
WHERE @H < 23;