SELECT CAR_ID, CAR_TYPE, FLOOR(CAR.DAILY_FEE * 30 * ((100 - CAR.DISCOUNT_RATE) / 100)) AS FEE
FROM (SELECT DISTINCT(C.CAR_ID), C.CAR_TYPE, C.DAILY_FEE, D.DISCOUNT_RATE
      FROM CAR_RENTAL_COMPANY_CAR C,
           CAR_RENTAL_COMPANY_RENTAL_HISTORY H,
           CAR_RENTAL_COMPANY_DISCOUNT_PLAN D
      WHERE C.CAR_ID = H.CAR_ID
        AND D.CAR_TYPE = C.CAR_TYPE
        AND C.CAR_ID NOT IN (
          SELECT CAR_ID
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
          WHERE END_DATE > "2022-11-01" AND START_DATE < "2022-12-01"
      )
        AND C.CAR_TYPE IN ("세단" ,"SUV")
        AND D.DURATION_TYPE = "30일 이상") CAR
WHERE CAR.DAILY_FEE * 30 * ((100 - CAR.DISCOUNT_RATE) / 100) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;